/* This file was automatically generated from XML paramdefs. */
#ifndef _PARAMDEF_MAP_DEFAULT_INFO_PARAM_ST_H
#define _PARAMDEF_MAP_DEFAULT_INFO_PARAM_ST_H
#pragma once
#include <inttypes.h>

// Data Version: 6
// Is Big Endian: False
// Is Unicode: True
// Format Version: 203
struct MAP_DEFAULT_INFO_PARAM_ST {

	// NAME: Do you remove it from the NT version output? - NT版出力から外すか
	// DESC: Parameters marked with ○ are excluded in the NT version package. - ○をつけたパラメータをNT版パッケージでは除外します
	uint8_t disableParam_NT: 1;

	// NAME: Reserve for package output 1 - パッケージ出力用リザーブ1
	// DESC: Reserve for package output 1 - パッケージ出力用リザーブ1
	uint8_t disableParamReserve1: 7;

	// NAME: Reserve for package output 2 - パッケージ出力用リザーブ2
	// DESC: Reserve for package output 2 - パッケージ出力用リザーブ2
	uint8_t disableParamReserve2[3];

	// NAME: Fast travel permission flag ID - ファストトラベル許可フラグID
	// DESC: Fast travel permission flag ID - ファストトラベル許可フラグID
	uint32_t EnableFastTravelEventFlagId;

	// NAME: Weather lottery time offset (in-game seconds) - 天候抽選時間オフセット(インゲーム秒)
	// DESC: Offset for weather lottery time (unit: in-game seconds). Divide by the in-game time scale of the game properties to get real time - 天候抽選時間にかかるオフセット(単位：インゲーム秒)。ゲームプロパティのインゲーム時間スケールで割ると現実時間になります
	int32_t WeatherLotTimeOffsetIngameSeconds;

	// NAME: ID for limiting the generation of weather generation assets - 天候生成アセット生成制限用ID
	// DESC: ID used to limit the generation of assets generated by the weather asset generation parameter .xlsm - 天候アセット生成パラメータ.xlsmで生成されるアセットの生成制限に使うID
	int8_t WeatherCreateAssetLimitId;

	// NAME: Map visibility type - マップ視界タイプ
	// DESC: Map visibility type - マップ視界タイプ
	uint8_t MapAiSightType;

	// NAME: Sound indoor, complete indoor distribution - サウンド屋内、完全屋内振り分け
	// DESC: Set whether to divide the map GD setting "indoor" into "indoor" or "completely indoor" for sound (SEQ09833). - マップGD設定の「屋内」をサウンド用の「屋内」、「完全屋内」どちらに振り分けるかを設定します(SEQ09833)
	uint8_t SoundIndoorType;

	// NAME: Reverb default settings - リバーブデフォルト設定
	// DESC: Specifies the reverb default type for this map - このマップのリバーブデフォルトタイプを指定します
	int8_t ReverbDefaultType;

	// NAME: Location information for BGM - BGM用場所情報
	// DESC: Specify location default information for BGM - BGM用の場所デフォルト情報を指定します
	int16_t BgmPlaceInfo;

	// NAME: Location information for environmental sounds - 環境音用場所情報
	// DESC: Specifies location default information for ambient sounds - 環境音用の場所デフォルト情報を指定します
	int16_t EnvPlaceInfo;

	// NAME: Map addition bank ID - マップ追加バンクID
	// DESC: Specify the ID of the "map addition bank" of the sound to be additionally loaded (-1: no map addition bank) (SEQ15725) - 追加で読み込むサウンドの「マップ追加バンク」のIDを指定します(-1:マップ追加バンクなし)(SEQ15725)
	int32_t MapAdditionalSoundBankId;

	// NAME: Map height information for sound [m] - サウンド用マップ高さ情報[m]
	// DESC: Map height information for sound [m] (SEQ15727) - サウンド用マップ高さ情報[m](SEQ15727)
	int16_t MapHeightForSound;

	// NAME: [For Legacy] Map Environment Map Time Blend Is Effective? - 【レガシー用】マップ環境マップ時間ブレンド有効か？
	// DESC: Specifies whether to time blend the environment map. Only Texure in the 0th time zone is shot and used. GPU load and memory are reduced. This setting is valid only for Legacy (m00-m49) (SEQ16464). - 環境マップの時間ブレンドを行うかを指定します。0番の時間帯のTexureだけが撮影、使用されます。GPU負荷,メモリが軽減されます。レガシー(m00-m49)のみ有効な設定です(SEQ16464)
	uint8_t IsEnableBlendTimezoneEnvmap;

	// NAME: GI resolution overwrite setting _XSS platform - GI解像度上書き設定_XSSプラット
	// DESC: Overwrites the GI resolution used in XSS (Xbox SeriesS, Lockhart) - XSS(Xbox SeriesS,Lockhart)で使用するGI解像度上書きします
	int8_t OverrideGIResolution_XSS;

	// NAME: Map high hit switching judgment AABB_width Depth (XZ) [m] - マップハイヒット切り替判定AABB_幅奥行き(XZ)[m]
	// DESC: Map high hit switching judgment AABB_width Depth (XZ) [m] (SEQ16295) - マップハイヒット切り替判定AABB_幅奥行き(XZ)[m](SEQ16295)
	float MapLoHiChangeBorderDist_XZ;

	// NAME: Map high hit switching judgment AABB_ height (Y) [m] - マップハイヒット切り替え判定AABB_高さ(Y)[m]
	// DESC: Map high hit switching judgment AABB_ height (Y) [m] (SEQ16295) - マップハイヒット切り替え判定AABB_高さ(Y)[m](SEQ16295)
	float MapLoHiChangeBorderDist_Y;

	// NAME: Map high hit switching judgment play distance [m] - マップハイヒット切り替え判定遊び距離[m]
	// DESC: Map high hit switching judgment play distance [m]. Normally the default should be fine. For smaller AABB, adjust as needed. If the play is too small, switching will occur frequently. Not expected if larger than AABB size (SEQ 16295) - マップハイヒット切り替え判定遊び距離[m]。通常はデフォルトでいいはず。小さいAABBの場合は必要に応じて調整してください。遊びがあまりに小さいと頻繁に切り替えが起こります。AABBサイズより大きい場合は想定してません(SEQ16295)
	float MapLoHiChangePlayDist;

	// NAME: Number of pixels to be judged on the back side in automatic drawing group calculation - 自動描画グループ計算で、裏面判定となるピクセル数
	// DESC: Number of pixels to be judged on the back side in automatic drawing group calculation - 自動描画グループ計算で、裏面判定となるピクセル数
	uint32_t MapAutoDrawGroupBackFacePixelNum;

	// NAME: Player Light Intensity Scale Value - Playerライト強度スケール値
	// DESC: Specify the scale to be applied to the PC and PC horse resident light source on this map (SEQ16562). - このマップでPC、PC馬常駐光源にかけるスケールを指定します(SEQ16562)
	float PlayerLigntScale;

	// NAME: Does the Player light intensity scale change depending on the time zone? - 時間帯によるPlayerライト強度スケール変化をするか？
	// DESC: Does this map change the Player light intensity scale depending on the PC, PC horse resident light source, and time zone? (SEQ 16562) - このマップでPC、PC馬常駐光源、時間帯によるPlayerライト強度スケール変化をするか？を指定します(SEQ16562)
	uint8_t IsEnableTimezonnePlayerLigntScale;

	// NAME: Do you want to disable automatic cliff wind SE? - 自動崖風SE無効にするか？
	// DESC: Do you want to disable automatic cliff wind SE? (SEQ15729) - 自動崖風SE無効にするか？(SEQ15729)
	uint8_t isDisableAutoCliffWind;

	// NAME: Open character activation limit_evaluation value threshold - オープンキャラアクティベート制限_評価値閾値
	// DESC: Open character activation limit_evaluation value threshold - オープンキャラアクティベート制限_評価値閾値
	int16_t OpenChrActivateThreshold;

	// NAME: Mimicry probability parameter ID by map - マップ別擬態確率パラメータID
	// DESC: Mimicry probability parameter ID by map (SEQ22471) - マップ別擬態確率パラメータID(SEQ22471)
	int32_t MapMimicryEstablishmentParamId;

	// NAME: GI resolution overwrite setting _XSX platform - GI解像度上書き設定_XSXプラット
	// DESC: Overwrites the GI resolution used on XSX (Xbox Series X, Anaconda) - XSX(Xbox SeriesX,Anaconda)で使用するGI解像度上書きします
	int8_t OverrideGIResolution_XSX;

	// NAME: Reserve - リザーブ
	// DESC: Reserve - リザーブ
	uint8_t Reserve[7];
};

#endif
